# Generated by Django 4.0.2 on 2022-03-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_agendamento_data_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
